### ISSUE TITLE
Same template getting rendered too many times than expected..

### ISSUE THREAD

**Issue by contactr2m** [CIGIHub/opencanada#633] opened 2017-07-05 22:38 UTC
I am trying to use OpenCanada code.
Just downloaded and installed as per given instructions. 
I was able to launch the site locally and add articles pages etc.

I am seeing 2 problems.
1. article block templates are getting rendered too many times.
2. home page never gets rendered after adding single article to article list page.
If there you remove the article page ie. no articles at all. homepage loads with no feature and other defaults.

After adding article and clicking on home page no template is rendered.. so i am unable to see whats exactly going on behind the curtains.
Can you please provide some info on this ? Any guidance would be great ...
**Is there any setting to be done for local environment ??**
After waiting for long time i get below error which is nothing but python is not coming out of infinite loop.

**In below sample articles/blocks/heading.html was rendered more than 100 times.. 
total templates rendered 167**. 

pthread_cond_wait: Resource busy
pthread_cond_wait: Resource busy
pthread_cond_wait: Resource busy
pthread_cond_wait: Resource busy
pthread_cond_wait: Resource busy
[05/Jul/2017 16:43:13] "GET / HTTP/1.1" 200 23800
[2017-07-05 16:43:13,006] - Broken pipe from ('127.0.0.1', 60706)

<img width="929" alt="screen shot 2017-07-05 at 6 26 17 pm" src="https://user-images.githubusercontent.com/13003246/27887589-7c55546c-61af-11e7-838e-0732fb5c8ab3.png">

themes/default/articles/article_page.html
/Users/admin/Projects/open/open/themes/templates/themes/default/articles/article_page.html
▶ Toggle context
articles/article_page.html
/Users/admin/Projects/open/open/articles/templates/articles/article_page.html
▶ Toggle context
base.html
/Users/admin/Projects/open/open/core/templates/base.html
▶ Toggle context
compressor/css_file.html
/Users/admin/Virtualenvs/Virtualenvs/cookie/lib/python2.7/site-packages/compressor/templates/compressor/css_file.html
▶ Toggle context
compressor/css_file.html
/Users/admin/Virtualenvs/Virtualenvs/cookie/lib/python2.7/site-packages/compressor/templates/compressor/css_file.html
▶ Toggle context
wagtailadmin/userbar/item_admin.html
/Users/admin/Virtualenvs/Virtualenvs/cookie/lib/python2.7/site-packages/wagtail/wagtailadmin/templates/wagtailadmin/userbar/item_admin.html
▶ Toggle context
wagtailadmin/userbar/item_base.html
/Users/admin/Virtualenvs/Virtualenvs/cookie/lib/python2.7/site-packages/wagtail/wagtailadmin/templates/wagtailadmin/userbar/item_base.html
▶ Toggle context
wagtailadmin/userbar/item_page_explore.html
/Users/admin/Virtualenvs/Virtualenvs/cookie/lib/python2.7/site-packages/wagtail/wagtailadmin/templates/wagtailadmin/userbar/item_page_explore.html
▶ Toggle context
wagtailadmin/userbar/item_base.html
/Users/admin/Virtualenvs/Virtualenvs/cookie/lib/python2.7/site-packages/wagtail/wagtailadmin/templates/wagtailadmin/userbar/item_base.html
▶ Toggle context
wagtailadmin/userbar/item_page_edit.html
/Users/admin/Virtualenvs/Virtualenvs/cookie/lib/python2.7/site-packages/wagtail/wagtailadmin/templates/wagtailadmin/userbar/item_page_edit.html
▶ Toggle context
wagtailadmin/userbar/item_base.html
/Users/admin/Virtualenvs/Virtualenvs/cookie/lib/python2.7/site-packages/wagtail/wagtailadmin/templates/wagtailadmin/userbar/item_base.html
▶ Toggle context
wagtailadmin/userbar/item_page_add.html
/Users/admin/Virtualenvs/Virtualenvs/cookie/lib/python2.7/site-packages/wagtail/wagtailadmin/templates/wagtailadmin/userbar/item_page_add.html
▶ Toggle context
wagtailadmin/userbar/item_base.html
/Users/admin/Virtualenvs/Virtualenvs/cookie/lib/python2.7/site-packages/wagtail/wagtailadmin/templates/wagtailadmin/userbar/item_base.html
▶ Toggle context
wagtailadmin/userbar/base.html
/Users/admin/Virtualenvs/Virtualenvs/cookie/lib/python2.7/site-packages/wagtail/wagtailadmin/templates/wagtailadmin/userbar/base.html
▶ Toggle context
core/header.html
/Users/admin/Projects/open/open/core/templates/core/header.html
▶ Toggle context
articles/includes/share_links.html
/Users/admin/Projects/open/open/articles/templates/articles/includes/share_links.html
▶ Toggle context
articles/includes/article-metadata.html
/Users/admin/Projects/open/open/articles/templates/articles/includes/article-metadata.html
▶ Toggle context
articles/includes/json-embed.html
/Users/admin/Projects/open/open/articles/templates/articles/includes/json-embed.html
▶ Toggle context
articles/includes/story-content.html
/Users/admin/Projects/open/open/articles/templates/articles/includes/story-content.html
▶ Toggle context
articles/includes/author_blurb.html
/Users/admin/Projects/open/open/articles/templates/articles/includes/author_blurb.html
▶ Toggle context
articles/blocks/heading.html
/Users/admin/Projects/open/open/articles/templates/articles/blocks/heading.html
▶ Toggle context
articles/blocks/heading.html
/Users/admin/Projects/open/open/articles/templates/articles/blocks/heading.html
▶ Toggle context
articles/blocks/heading.html
/Users/admin/Projects/open/open/articles/templates/articles/blocks/heading.html
▶ Toggle context
articles/blocks/heading.html
/Users/admin/Projects/open/open/articles/templates/articles/blocks/heading.html
▶ Toggle context
articles/blocks/heading.html
/Users/admin/Projects/open/open/articles/templates/articles/blocks/heading.html
▶ Toggle context
....
▶ Toggle context
articles/includes/advanced-content.html
/Users/admin/Projects/open/open/articles/templates/articles/includes/advanced-content.html
▶ Toggle context
articles/includes/related_articles.html
/Users/admin/Projects/open/open/articles/templates/articles/includes/related_articles.html
▶ Toggle context
core/footer.html
/Users/admin/Projects/open/open/core/templates/core/footer.html
▶ Toggle context

**Comment by albertoconnor** [comment] 2017-07-06 17:15
The home page appears empty because there is an error in the include block and through a quirk of how the theming system work, the entire home page is included in itself. This should be fixed in the coming month. You can get around this if your database is seeded correctly.

(sorry I don't currently have time to test and tell you what correctly means, but if you turn on logging you should be able to see the issues)

I am not convinced by your output that it is being rendered more than once, each block which gets rendered which causes something else to happen would likely reporting being on the same template. I would need more information to be sure.

**Comment by contactr2m** [comment] 2017-07-06 19:36
I attached pdb and looks like its HomePage::get_article_set() method. i see recursive call there, which seems to be a culprit. 
Its not coming out of that method. `pthread_cond_wait: Resource busy`

(Pdb)  home.get_article_set(3, 12, tt, [])
Current rows count 12
_fill_row current row, height ([<ArticlePage: test>], 1)
Current set [[<ArticlePage: test>]]
Current rows count 11
_fill_row current row, height ([], 0)  <--- row is 0 and no article as `test article` is already used.
Current set [[<ArticlePage: test>], []]
Current rows count 11   <--- so this row count never goes to 0, its always 11
_fill_row current row, height ([], 0)
Current set [[<ArticlePage: test>], [], []]
Current rows count 11
_fill_row current row, height ([], 0)
Current set [[<ArticlePage: test>], [], [], []]
Current rows count 11
_fill_row current row, height ([], 0)
Current set [[<ArticlePage: test>], [], [], [], []]
Current rows count 11
_fill_row current row, height ([], 0)
Current set [[<ArticlePage: test>], [], [], [], [], []]
Current rows count 11
_fill_row current row, height ([], 0)
Current set [[<ArticlePage: test>], [], [], [], [], [], []]

`current_set = []

        while rows > 0:
            row, height = self._fill_row(columns, article_list, used, rows)
            current_set.append(row)
            if height == 0:    <-- this is fixing it..
                break
            rows = rows - height`

(Pdb) Current rows count 12
_fill_row current row, height ([<ArticlePage: test>], 1)
Current set [[<ArticlePage: test>]]
Current rows count 11
_fill_row current row, height ([], 0)
Current set [[<ArticlePage: test>], []]

**Comment by albertoconnor** [comment] 2017-07-06 21:23
Hi Mani,

First off thanks so much for looking so deeply into this issue and providing a fix, I really appreciate it.

I was thinking of another set of issues which can cause the home page to render, but render blank, rather than take forever to render.

You fix looks good, and after some additional testing, I will look at including in master. If you want to make a formal PR that would be great.

I am curious about 1. article block templates are getting rendered too many times.

Can you flesh out what your experience is, and how you know article block templates are getting rendered too many times? On what page kind of pages/request do you see the issue.

With a bit more information there might be another fix in your future.

Thanks for your time, I appreciate it!

**Comment by contactr2m** [comment] 2017-07-07 15:32
> Can you flesh out what your experience is, and how you know article block templates are getting rendered too many times? On what page kind of pages/request do you see the issue.

Its happens when you display article page
http://127.0.0.1:8000/features/test2/
django debug toolbar -> Templates (165 rendered)

This is repeated 100+ times
>articles/blocks/heading.html
/Users/admin/Projects/open/open/articles/templates/articles/blocks/heading.html
▶ Toggle context

I am sure heading block is rendered for related articles too but there are only 2. Total 3 article pages.

I think its trying to get info for in_depth, story, series pages too. but none of them exists

still looking

**Comment by albertoconnor** [comment] 2017-07-07 18:58
Here the heading isn't a page header or the title of the article, it is the heading block in the article stream field. The body of your piece. I see something similar (over 100 renderings) for the paragraph block template in one of the articles I checked out with Debug Toolbar.

I have a theory that this is being caused by the system which pushed down theme data, which is being removed soon. I will try to check again after those changes have been made.

Let me know if you find anything else.

I have created a PR for your first fix suggestion after testing against a full database. It contains one other optimization, though I think the whole home page rendering code needs to be rewritten.

Thanks,
Albert

**Comment by contactr2m** [comment] 2017-07-07 19:41
Thanks for the PR. 

Right its heading block. 
So for eg. http://127.0.0.1:8000/features/test2/ article page is being rendered and there is one related article (test4) with only one paragraph as a streamfield. 
Then below pattern is seen.
test2 articles loads with expected templates.
In related articles sections i do see test4 article too but articles/blocks/paragraph template is rendered 100+ times.. 

So for sure its happening when related articles tag is called.

**Comment by albertoconnor** [comment] 2017-07-07 20:15
That is useful, I'll try to take a look next week

**Comment by gabrieltanchen** [comment] 2021-05-26 18:11
Closing as this repository is now archived.

**Closed by gabrieltanchen** 2021-05-26 18:11 UTC
